version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0"
    volumes:
      - /etc/prometheus:/etc/prometheus
    ports:
      - "9090:9090"  # Exposing Prometheus web UI on port 9090
  app:
    build: /root/devops_exercise/inventory_server


